# Generated by Django 5.0.1 on 2025-01-20 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="商品名称"),
                ),
                ("product_desc", models.TextField(verbose_name="商品描述")),
                (
                    "product_tag",
                    models.CharField(
                        choices=[
                            ("Living", "Living"),
                            ("Food", "Food"),
                            ("Clothes", "Clothes"),
                            ("Baby", "Baby"),
                            ("Health", "Health"),
                            ("Digital", "Digital"),
                            ("Sports", "Sports"),
                        ],
                        max_length=100,
                        verbose_name="分类",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("images", models.JSONField(default=list, verbose_name="商品图片")),
                ("stock_quantity", models.IntegerField(verbose_name="库存数量")),
                (
                    "stock_status",
                    models.CharField(max_length=50, verbose_name="库存状态"),
                ),
                ("low_stock_threshold", models.IntegerField(verbose_name="低库存阈值")),
                (
                    "product_details",
                    models.JSONField(default=list, verbose_name="商品详细信息"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "Active"),
                            ("INA", "Inactive"),
                            ("OOS", "Out of stock"),
                        ],
                        default="INA",
                        max_length=20,
                        verbose_name="商品状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品列表",
            },
        ),
    ]
