# Generated by Django 5.0.1 on 2025-01-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock_status",
        ),
    ]
