# Generated by Django 5.0.1 on 2025-01-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_stock_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_rating",
            field=models.FloatField(default=0.0, verbose_name="商品评分"),
        ),
    ]
