# Generated by Django 5.0.1 on 2025-01-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_product_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_tag",
        ),
    ]
