# Generated by Django 5.0.1 on 2025-01-21 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("product", "0004_remove_product_product_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                default="26c5e401d1914205b2c9b551b090d6c8",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="category.subcategory",
                verbose_name="商品分类",
            ),
        ),
    ]
