# Generated by Django 5.0.1 on 2025-01-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_remove_category_avail_subcategory_sub_cate_image"),
        ("product", "0005_product_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="category.subcategory",
                verbose_name="商品分类",
            ),
        ),
    ]
