# Generated by Django 5.0.1 on 2025-01-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="avail",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="sub_cate_image",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
