# Generated by Django 5.0.1 on 2025-01-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_remove_category_avail_subcategory_sub_cate_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(default="0", max_length=1),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="status",
            field=models.CharField(default="0", max_length=1),
        ),
    ]
