# Generated by Django 5.0.1 on 2025-01-17 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "User list"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="agree_to_privacy_policy",
        ),
        migrations.AddField(
            model_name="user",
            name="birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="D:\\Code\\Python\\DjangoProject\\ecommerce\\media200.png",
                null=True,
                upload_to="D:\\Code\\Python\\DjangoProject\\ecommerce\\media",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(default="3", max_length=1),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=14)),
                ("country", models.CharField(max_length=50)),
                ("province", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("detailed", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "address_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Address list",
            },
        ),
    ]
