# Generated by Django 5.0.1 on 2025-01-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_and_more"),
    ]

    operations = []
