# Generated by Django 5.0.1 on 2025-01-20 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20250117_2049"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户列表"},
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="/media/200.png", null=True, upload_to="profile/"
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
