# Generated by Django 5.0.1 on 2025-01-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_options_user_user_type_alter_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
    ]
